import { describe, expect, test } from 'bun:test';
import ts from 'typescript';
import type { FieldIR } from '../contracts.js';
import { emitGeneratedModule, relativeTypeImportSpecifier } from './emit.js';

const fields: readonly FieldIR[] = [
  {
    propertyPath: ['port'],
    defaultsPath: ['server', 'port'],
    envName: 'APP_PORT',
    kind: { type: 'number' },
    required: true,
    secret: false,
    hasDefault: true,
    defaultValue: 3000,
    optionalParents: [],
    location: { file: '/tmp/project/src/config.ts', line: 4, column: 3 },
  },
  {
    propertyPath: ['token'],
    defaultsPath: ['token'],
    envName: 'APP_TOKEN',
    kind: { type: 'string' },
    required: false,
    secret: true,
    hasDefault: false,
    optionalParents: [],
    location: { file: '/tmp/project/src/config.ts', line: 5, column: 3 },
  },
];

describe('generated module emission', () => {
  test('emits the exact stable module without source locations or timestamps', () => {
    const output = emitGeneratedModule({
      rootExport: { kind: 'named', name: 'AppConfig' },
      rootName: 'InternalAppConfig',
      typeImport: '../config.js',
      fields,
      compiledDefaults: { port: 8080, nested: { enabled: true } },
      fingerprint: '0123456789abcdef',
    });

    expect(output).toBe(`// Generated by typespun-codegen. Do not edit.
// Schema fingerprint: 0123456789abcdef

import { createLoader, type GeneratedSchema } from 'typespun/generated';
import type { AppConfig as TypespunConfig } from '../config.js';

export type Config = TypespunConfig;

const schema = {
  "compiledDefaults": {
    "nested": {
      "enabled": true
    },
    "port": 8080
  },
  "fields": [
    {
      "defaultValue": 3000,
      "defaultsPath": [
        "server",
        "port"
      ],
      "envName": "APP_PORT",
      "hasDefault": true,
      "kind": {
        "type": "number"
      },
      "optionalParents": [],
      "propertyPath": [
        "port"
      ],
      "required": true,
      "secret": false
    },
    {
      "defaultsPath": [
        "token"
      ],
      "envName": "APP_TOKEN",
      "hasDefault": false,
      "kind": {
        "type": "string"
      },
      "optionalParents": [],
      "propertyPath": [
        "token"
      ],
      "required": false,
      "secret": true
    }
  ],
  "protocolVersion": 1
} as const satisfies GeneratedSchema;

export const loadConfig = createLoader<Config>(schema);
`);
    expect(output).not.toContain('/tmp/project');
    expect(output).not.toMatch(/generated at|20\d\d-/i);
    expect(output).not.toContain('InternalAppConfig');
  });

  test('imports a default root through a private stable binding', () => {
    expect(
      emitGeneratedModule({
        rootExport: { kind: 'default' },
        rootName: 'AppConfig',
        typeImport: '../config.mjs',
        fields: [],
        compiledDefaults: {},
        fingerprint: 'abc',
      }),
    ).toContain("import type TypespunConfig from '../config.mjs';");
  });

  test.each([
    ['config.ts', 'typespun.ts', '../config.js'],
    ['config.mts', 'typespun.mts', '../config.mjs'],
    ['config.cts', 'typespun.cts', '../config.cjs'],
  ])(
    'uses the emitted NodeNext extension for %s',
    (inputName, outputName, expected) => {
      expect(
        relativeTypeImportSpecifier(
          `/project/src/${inputName}`,
          `/project/src/generated/${outputName}`,
          {
            module: ts.ModuleKind.NodeNext,
            moduleResolution: ts.ModuleResolutionKind.NodeNext,
          },
        ),
      ).toBe(expected);
    },
  );

  test('uses NodeNext emitted specifiers when module resolution is implicit', () => {
    expect(
      relativeTypeImportSpecifier(
        '/project/src/config.ts',
        '/project/src/generated/typespun.ts',
        { module: ts.ModuleKind.NodeNext },
      ),
    ).toBe('../config.js');
  });
});
