import ts from 'typescript';
import type { FieldSchema } from 'typespun/schema';
import type { FieldIR, RootExport } from '../contracts.js';
import { dirname, extname, relative } from '../internal/path.js';
import { stableJson } from './fingerprint.js';

export interface EmitGeneratedModuleOptions {
  readonly rootExport: RootExport;
  readonly rootName: string;
  readonly typeImport: string;
  readonly fields: readonly FieldIR[];
  readonly compiledDefaults: Readonly<Record<string, unknown>>;
  readonly fingerprint: string;
}

export function emitGeneratedModule(
  options: EmitGeneratedModuleOptions,
): string {
  const fields = options.fields.map(stripLocation);
  const schema = {
    compiledDefaults: options.compiledDefaults,
    fields,
    protocolVersion: 1,
  };
  const typeImport =
    options.rootExport.kind === 'default'
      ? `import type TypespunConfig from ${quote(options.typeImport)};`
      : `import type { ${formatExportName(options.rootExport.name)} as TypespunConfig } from ${quote(options.typeImport)};`;

  return `// Generated by typespun-codegen. Do not edit.
// Schema fingerprint: ${options.fingerprint}

import { createLoader, type GeneratedSchema } from 'typespun/generated';
${typeImport}

export type Config = TypespunConfig;

const schema = ${stableJson(schema, 2)} as const satisfies GeneratedSchema;

export const loadConfig = createLoader<Config>(schema);
`;
}

export function relativeTypeImportSpecifier(
  inputPath: string,
  outputPath: string,
  compilerOptions: ts.CompilerOptions,
): string {
  const relativePath = relative(dirname(outputPath), inputPath);
  const withoutExtension = relativePath.slice(0, -extname(relativePath).length);
  const prefix = withoutExtension.startsWith('.')
    ? withoutExtension
    : `./${withoutExtension}`;

  return `${prefix}${usesNodeEmittedSpecifiers(compilerOptions) ? emittedExtension(inputPath) : ''}`;
}

function stripLocation(field: FieldIR): FieldSchema {
  const { location: _location, ...schemaField } = field;
  return schemaField;
}

function usesNodeEmittedSpecifiers(options: ts.CompilerOptions): boolean {
  return (
    options.moduleResolution === ts.ModuleResolutionKind.Node16 ||
    options.moduleResolution === ts.ModuleResolutionKind.NodeNext ||
    options.moduleResolution === ts.ModuleResolutionKind.Bundler ||
    (options.moduleResolution === undefined &&
      (options.module === ts.ModuleKind.Node16 ||
        options.module === ts.ModuleKind.NodeNext))
  );
}

function emittedExtension(path: string): '.js' | '.mjs' | '.cjs' {
  switch (extname(path)) {
    case '.mts':
      return '.mjs';
    case '.cts':
      return '.cjs';
    default:
      return '.js';
  }
}

function formatExportName(name: string): string {
  return /^[$A-Z_a-z][$\w]*$/u.test(name) ? name : quote(name);
}

function quote(value: string): string {
  const json = stableJson(value);
  return `'${json.slice(1, -1).replace(/'/g, "\\'").replace(/\\"/g, '"')}'`;
}
